apiVersion: v1
kind: Service
metadata:
  name: capstone-app
  labels:
    app: capstone

spec:
  ports:
  - port: 8080
    targetPort: 80
  selector:
    app: capstone
  type: LoadBalancer