apiVersion: v1
kind: Service
metadata:
  name: capstone-app
  labels:
    app: capstone

spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: capstone
  type: LoadBalancer